### ISSUE TITLE
ModuleNotFoundError: No module named 'openai.types.beta.threads.message_content'

### ISSUE THREAD

**Issue by uptang14** [filip-michalsky/SalesGPT#147]
when running "python3 run.py --verbose True --config examples/example_cn_agent_setup.json" 
prompt：
Traceback (most recent call last):
  File "/mnt/workspace/SalesGPT/run.py", line 10, in <module>
    from salesgpt.agents import SalesGPT
  File "/mnt/workspace/SalesGPT/salesgpt/agents.py", line 17, in <module>
    from litellm import acompletion
  File "/opt/conda/envs/salesgpt/lib/python3.10/site-packages/litellm/__init__.py", line 761, in <module>
    from .llms.openai import OpenAIConfig, OpenAITextCompletionConfig, MistralConfig
  File "/opt/conda/envs/salesgpt/lib/python3.10/site-packages/litellm/llms/openai.py", line 28, in <module>
    from ..types.llms.openai import *
  File "/opt/conda/envs/salesgpt/lib/python3.10/site-packages/litellm/types/llms/openai.py", line 12, in <module>
    from openai.types.beta.threads.message_content import MessageContent
ModuleNotFoundError: No module named 'openai.types.beta.threads.message_content'

**Comment by Mdabo1** [comment]
delete openai and install the newest version, helped for me

```
pip uninstall openai 
pip install openai 
```

**Comment by uptang14** [comment]
Thank you for your reply.
But after executing the above code, the following prompt appears：ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
salesgpt 0.1.2 requires openai==1.7.0, but you have openai 1.30.1 which is incompatible.
In addition, when running "python3 run.py --verbose True --config examples/example_cn_agent_setup.json" ，the following prompt appears：Traceback (most recent call last):
  File "/mnt/workspace/SalesGPT/run.py", line 10, in <module>
    from salesgpt.agents import SalesGPT
  File "/mnt/workspace/SalesGPT/salesgpt/agents.py", line 27, in <module>
    from salesgpt.tools import get_tools, setup_knowledge_base
  File "/mnt/workspace/SalesGPT/salesgpt/tools.py", line 4, in <module>
    import boto3
ModuleNotFoundError: No module named 'boto3'

**Comment by hezuogongying** [comment]
安装 boto3

**Comment by chemik-bit** [comment]
Hey @uptang14 has the issue been fixed? Hopefully the dependency improvements should have fixed this. :)
