### ISSUE TITLE
ModuleNotFoundError: No module named 'openai.types.beta.threads.message_content'

### ISSUE THREAD

**Issue by zoltiq** [filip-michalsky/SalesGPT#169]
I installed exactly according to the instructions (without the docker)
after activation with the command:
python run.py --verbose True --config examples/example_agent_setup.json

a stack of error messages appears:

Traceback (most recent call last):
  File "C:\Users\Sebol\Desktop\chat-php\langchain\full_salesGPT\SalesGPT\run.py", line 10, in <module>
    from salesgpt.agents import SalesGPT
  File "C:\Users\Sebol\Desktop\chat-php\langchain\full_salesGPT\SalesGPT\salesgpt\agents.py", line 17, in <module>
    from litellm import acompletion
  File "C:\Users\Sebol\Desktop\chat-php\langchain\full_salesGPT\env\Lib\site-packages\litellm\__init__.py", line 764, in <module>
    from .llms.openai import OpenAIConfig, OpenAITextCompletionConfig, MistralConfig
  File "C:\Users\Sebol\Desktop\chat-php\langchain\full_salesGPT\env\Lib\site-packages\litellm\llms\openai.py", line 28, in <module>
    from ..types.llms.openai import *
  File "C:\Users\Sebol\Desktop\chat-php\langchain\full_salesGPT\env\Lib\site-packages\litellm\types\llms\openai.py", line 12, in <module>
    from openai.types.beta.threads.message_content import MessageContent
ModuleNotFoundError: No module named 'openai.types.beta.threads.message_content'

Please help how to deal with this.

**Comment by ZhanarBaken** [comment]
change litellm>=1.10.2 to litellm==1.10.2

**Comment by zackscat** [comment]
Have you solved this problem? I've run into it too.

**Comment by mmasoomi-glitch** [comment]
test
