### ISSUE TITLE
Error in run.py when using --verbose True and example_agent_setup.json

### ISSUE THREAD

**Issue by splendidcomputer** [filip-michalsky/SalesGPT#57]
Hi,

I encountered an issue while running the code with the following command:

```
(venv) (sales) mostafa@aorus:~/programming/progwise/sales-gpt/python/SalesGPT$ python run.py --verbose True --config examples/example_agent_setup.json
```

The error message I received is as follows:

```
/home/mostafa/programming/progwise/sales-gpt/python/SalesGPT/venv/lib/python3.11/site-packages/langchain/__init__.py:38: UserWarning: Importing LLMChain from langchain root module is no longer supported.
  warnings.warn(
/home/mostafa/programming/progwise/sales-gpt/python/SalesGPT/venv/lib/python3.11/site-packages/langchain/__init__.py:38: UserWarning: Importing LLMChain from langchain root module is no longer supported.
  warnings.warn(
/home/mostafa/programming/progwise/sales-gpt/python/SalesGPT/venv/lib/python3.11/site-packages/langchain/__init__.py:38: UserWarning: Importing PromptTemplate from langchain root module is no longer supported.
  warnings.warn(
Traceback (most recent call last):
  File "/home/mostafa/programming/progwise/sales-gpt/python/SalesGPT/run.py", line 5, in <module>
    from salesgpt.agents import SalesGPT
  File "/home/mostafa/programming/progwise/sales-gpt/python/SalesGPT/salesgpt/agents.py", line 35, in <module>
    class SalesGPT(Chain, BaseModel):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
```

It appears that there's a metaclass conflict issue in the `SalesGPT` class in the `agents.py` file. I'm not sure if this is specific to my environment or if it's a general issue with the codebase. Could someone please take a look and provide guidance on how to resolve this error?

Thank you!

**Comment by filip-michalsky** [comment]
@splendidcomputer this has to do with `pydantic` upgrade. Pushing fix shortly.
