### ISSUE TITLE
Not able to run even following all the steps of installation 

### ISSUE THREAD

**Issue by HugoAVaz** [filip-michalsky/SalesGPT#68]
Ted Lasso:
Traceback (most recent call last):
  File "/root/SalesGPT/run.py", line 67, in <module>
    sales_agent.step()
  File "/root/SalesGPT/salesgpt/logger.py", line 34, in wrapper
    result = func(*args, **kwargs)  # Function execution
  File "/root/SalesGPT/salesgpt/agents.py", line 107, in step
    self._call(inputs={})
  File "/root/SalesGPT/salesgpt/agents.py", line 246, in _call
    ai_message = self.sales_conversation_utterance_chain.run(
  File "/usr/local/lib/python3.9/dist-packages/langchain/chains/base.py", line 510, in run
    return self(kwargs, callbacks=callbacks, tags=tags, metadata=metadata)[
  File "/usr/local/lib/python3.9/dist-packages/langchain/chains/base.py", line 310, in __call__
    raise e
  File "/usr/local/lib/python3.9/dist-packages/langchain/chains/base.py", line 304, in __call__
    self._call(inputs, run_manager=run_manager)
  File "/usr/local/lib/python3.9/dist-packages/langchain/chains/llm.py", line 108, in _call
    response = self.generate([inputs], run_manager=run_manager)
  File "/usr/local/lib/python3.9/dist-packages/langchain/chains/llm.py", line 120, in generate
    return self.llm.generate_prompt(
  File "/usr/local/lib/python3.9/dist-packages/langchain/chat_models/base.py", line 459, in generate_prompt
    return self.generate(prompt_messages, stop=stop, callbacks=callbacks, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/langchain/chat_models/base.py", line 349, in generate
    raise e
  File "/usr/local/lib/python3.9/dist-packages/langchain/chat_models/base.py", line 339, in generate
    self._generate_with_cache(
  File "/usr/local/lib/python3.9/dist-packages/langchain/chat_models/base.py", line 492, in _generate_with_cache
    return self._generate(
  File "/usr/local/lib/python3.9/dist-packages/langchain/chat_models/litellm.py", line 306, in _generate
    response = self.completion_with_retry(
  File "/usr/local/lib/python3.9/dist-packages/langchain/chat_models/litellm.py", line 233, in completion_with_retry
    retry_decorator = _create_retry_decorator(self, run_manager=run_manager)
  File "/usr/local/lib/python3.9/dist-packages/langchain/chat_models/litellm.py", line 70, in _create_retry_decorator
    litellm.APIConnectionError,
AttributeError: module 'litellm' has no attribute 'APIConnectionError'

1 - made touch .env
2 - copied api key there
3 - followed this steps -> 
Make sure your have a python 3.10+ and run:

pip install -r requirements.txt

additional info: Python 3.11.2

**Comment by chemik-bit** [comment]
We have recently updated our dependency management to enhance the project's performance and reliability. To benefit from these improvements, we invite you to download the latest version of the repository.

Should you encounter any issues after this update, please do not hesitate to report them back here.

**Comment by filip-michalsky** [comment]
@HugoAVaz thanks for your patience! please contact me or @chemik-bit  if you have any other issues. I will be closing this issue now since its stale. Thank you!
