### ISSUE TITLE
Calling deprecated endpoint  results in "POST https://api.openai.com/v1/completions "HTTP/1.1 404 Not Found"

### ISSUE THREAD

**Issue by roperi** [filip-michalsky/SalesGPT#96]
I was getting  `text-davinci-003` deprecated errors when running the example code from README file. 

I manually updated all references to `text-davinci-003` to `gpt-3.5-003` in  the `langchain/llms/openai.py` package file.

But can't figure out where do i have to update the endpoint from `v1/completions` to `v1/chat/completions`. The lanchain library fixed this issue in later versions but SalesGPT requires an old version one. 

Anyway, here's the problem:

```
>>> sales_agent.determine_conversation_stage() # optional for demonstration, built into the prompt
httpx 2024-01-27 17:23:58,074 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
Conversation Stage ID: 5
Conversation Stage: Solution presentation: Based on the prospect's needs, present your product/service as the solution that can address their pain points.
salesgpt.logger 2024-01-27 17:23:58,081 - INFO - Running determine_conversation_stage: --- 0.7663512229919434 seconds ---
```

Everything seems alright, right? But  it then always fails in the next step. 

```
>>> sales_agent.step()
httpx 2024-01-27 17:24:00,111 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
httpx 2024-01-27 17:24:01,546 - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
httpx 2024-01-27 17:24:01,914 - INFO - HTTP Request: POST https://api.openai.com/v1/completions "HTTP/1.1 404 Not Found"
```

Here's the entire traceback:

```
httpx 2024-01-27 17:24:01,914 - INFO - HTTP Request: POST https://api.openai.com/v1/completions "HTTP/1.1 404 Not Found"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/workspace/SalesGPT/salesgpt/logger.py", line 34, in wrapper
    result = func(*args, **kwargs)  # Function execution
  File "/home/user/workspace/SalesGPT/salesgpt/agents.py", line 107, in step
    self._call(inputs={})
  File "/home/user/workspace/SalesGPT/salesgpt/agents.py", line 231, in _call
    ai_message = self.sales_agent_executor.run(
  File "/home/user/.virtualenvs/SalesGPT/lib/python3.10/site-packages/langchain/chains/base.py", line 512, in run
    return self(kwargs, callbacks=callbacks, tags=tags, metadata=metadata)[
  File "/home/user/.virtualenvs/SalesGPT/lib/python3.10/site-packages/langchain/chains/base.py", line 312, in __call__
    raise e
  File "/home/user/.virtualenvs/SalesGPT/lib/python3.10/site-packages/langchain/chains/base.py", line 306, in __call__
    self._call(inputs, run_manager=run_manager)
  File "/home/user/.virtualenvs/SalesGPT/lib/python3.10/site-packages/langchain/agents/agent.py", line 1312, in _call
    next_step_output = self._take_next_step(
  File "/home/user/.virtualenvs/SalesGPT/lib/python3.10/site-packages/langchain/agents/agent.py", line 1038, in _take_next_step
    [
  File "/home/user/.virtualenvs/SalesGPT/lib/python3.10/site-packages/langchain/agents/agent.py", line 1038, in <listcomp>
    [
  File "/home/user/.virtualenvs/SalesGPT/lib/python3.10/site-packages/langchain/agents/agent.py", line 1134, in _iter_next_step
    observation = tool.run(
  File "/home/user/.virtualenvs/SalesGPT/lib/python3.10/site-packages/langchain_core/tools.py", line 365, in run
    raise e
  File "/home/user/.virtualenvs/SalesGPT/lib/python3.10/site-packages/langchain_core/tools.py", line 337, in run
    self._run(*tool_args, run_manager=run_manager, **tool_kwargs)
  File "/home/user/.virtualenvs/SalesGPT/lib/python3.10/site-packages/langchain_core/tools.py", line 510, in _run
    self.func(
  File "/home/user/.virtualenvs/SalesGPT/lib/python3.10/site-packages/langchain/chains/base.py", line 507, in run
    return self(args[0], callbacks=callbacks, tags=tags, metadata=metadata)[
  File "/home/user/.virtualenvs/SalesGPT/lib/python3.10/site-packages/langchain/chains/base.py", line 312, in __call__
    raise e
  File "/home/user/.virtualenvs/SalesGPT/lib/python3.10/site-packages/langchain/chains/base.py", line 306, in __call__
    self._call(inputs, run_manager=run_manager)
  File "/home/user/.virtualenvs/SalesGPT/lib/python3.10/site-packages/langchain/chains/retrieval_qa/base.py", line 141, in _call
    answer = self.combine_documents_chain.run(
  File "/home/user/.virtualenvs/SalesGPT/lib/python3.10/site-packages/langchain/chains/base.py", line 512, in run
    return self(kwargs, callbacks=callbacks, tags=tags, metadata=metadata)[
  File "/home/user/.virtualenvs/SalesGPT/lib/python3.10/site-packages/langchain/chains/base.py", line 312, in __call__
    raise e
  File "/home/user/.virtualenvs/SalesGPT/lib/python3.10/site-packages/langchain/chains/base.py", line 306, in __call__
    self._call(inputs, run_manager=run_manager)
  File "/home/user/.virtualenvs/SalesGPT/lib/python3.10/site-packages/langchain/chains/combine_documents/base.py", line 123, in _call
    output, extra_return_dict = self.combine_docs(
  File "/home/user/.virtualenvs/SalesGPT/lib/python3.10/site-packages/langchain/chains/combine_documents/stuff.py", line 172, in combine_docs
    return self.llm_chain.predict(callbacks=callbacks, **inputs), {}
  File "/home/user/.virtualenvs/SalesGPT/lib/python3.10/site-packages/langchain/chains/llm.py", line 293, in predict
    return self(kwargs, callbacks=callbacks)[self.output_key]
  File "/home/user/.virtualenvs/SalesGPT/lib/python3.10/site-packages/langchain/chains/base.py", line 312, in __call__
    raise e
  File "/home/user/.virtualenvs/SalesGPT/lib/python3.10/site-packages/langchain/chains/base.py", line 306, in __call__
    self._call(inputs, run_manager=run_manager)
  File "/home/user/.virtualenvs/SalesGPT/lib/python3.10/site-packages/langchain/chains/llm.py", line 103, in _call
    response = self.generate([inputs], run_manager=run_manager)
  File "/home/user/.virtualenvs/SalesGPT/lib/python3.10/site-packages/langchain/chains/llm.py", line 115, in generate
    return self.llm.generate_prompt(
  File "/home/user/.virtualenvs/SalesGPT/lib/python3.10/site-packages/langchain_core/language_models/llms.py", line 516, in generate_prompt
    return self.generate(prompt_strings, stop=stop, callbacks=callbacks, **kwargs)
  File "/home/user/.virtualenvs/SalesGPT/lib/python3.10/site-packages/langchain_core/language_models/llms.py", line 666, in generate
    output = self._generate_helper(
  File "/home/user/.virtualenvs/SalesGPT/lib/python3.10/site-packages/langchain_core/language_models/llms.py", line 553, in _generate_helper
    raise e
  File "/home/user/.virtualenvs/SalesGPT/lib/python3.10/site-packages/langchain_core/language_models/llms.py", line 540, in _generate_helper
    self._generate(
  File "/home/user/.virtualenvs/SalesGPT/lib/python3.10/site-packages/langchain/llms/openai.py", line 455, in _generate
    response = completion_with_retry(
  File "/home/user/.virtualenvs/SalesGPT/lib/python3.10/site-packages/langchain/llms/openai.py", line 115, in completion_with_retry
    return llm.client.create(**kwargs)
  File "/home/user/.virtualenvs/SalesGPT/lib/python3.10/site-packages/openai/_utils/_utils.py", line 301, in wrapper
    return func(*args, **kwargs)
  File "/home/user/.virtualenvs/SalesGPT/lib/python3.10/site-packages/openai/resources/completions.py", line 559, in create
    return self._post(
  File "/home/user/.virtualenvs/SalesGPT/lib/python3.10/site-packages/openai/_base_client.py", line 1096, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/user/.virtualenvs/SalesGPT/lib/python3.10/site-packages/openai/_base_client.py", line 856, in request
    return self._request(
  File "/home/user/.virtualenvs/SalesGPT/lib/python3.10/site-packages/openai/_base_client.py", line 908, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: Error code: 404 - {'error': {'message': 'This is a chat model and not supported in the v1/completions endpoint. Did you mean to use v1/chat/completions?', 'type': 'invalid_request_error', 'param': 'model', 'code': None}}
```

**Comment by ZuzooVn** [comment]
@roperi The latest version available is Langchain 0.1.4, while SalesGPT is still utilizing an older version, Langchain 0.0.345.

In my opinion, it is highly recommended that you upgrade Langchain and all its dependencies to the latest version. 
Note: With the latest Langchain version upgrade, you might need to update your import structure. Langchain has made package structure updates, but implementing the changes is straightforward.

To simplify the process of upgrading your dependencies, I suggest utilizing one of two reliable tools:

- [Poetry Plugin Up](https://github.com/MousaZeidBaker/poetry-plugin-up): This plugin is specifically designed for Poetry-managed projects and streamlines the process of updating dependencies to their latest versions. 

- [Python Project Dependency Updater](https://github.com/wyattowalsh/poetry-dependency-updater): This Python script automates the task of updating all dependencies in your Poetry-managed project. It ensures that your project remains in sync with the latest versions of its dependencies, saving you time and effort.
